### ISSUE TITLE
Add hCaptcha via spm without Rx

### ISSUE THREAD

**Issue by vitys96** [hCaptcha/HCaptcha-ios-sdk#123]
Hi! How can I add hCaptcha via spm without RxSwift?
Here is my package.swift
<img width="1728" alt="image" src="https://github.com/hCaptcha/HCaptcha-ios-sdk/assets/36761441/2a23dc89-5dc2-4dad-8447-0a968aa1d789">

**Comment by CAMOBAP** [comment]
@vitys96 Thanks for the report, 

Unfortunately, it's a known issue of https://github.com/apple/swift-package-manager/issues/4759

The good news that `RxSwift` isn't actually be added to you app, it's just visible in `Package Dependencies` section of Xcode, because `spm` isn't smart enough yet to resolve such cases

So as far as I see from your `Package.swift` you don't use `HCaptcha_RxSwift` target directly `RxSwift` will not impact size of your application

Please let us know if you have any further issues/concerns
