### ISSUE TITLE
Enforce ES5 to ensure compatibility with old iOS versions

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/HCaptcha-ios-sdk#3]
iOS versions below 10.0 require ES5. This is way less than 1% of devices. Do we still care? Unclear, but it is a small amount of effort to stay compatible.

In the future, we may instead babelize the JS to ES5 to ensure compatibility with old iOS versions once we start using ES6 features.

**Comment by CAMOBAP** [comment]
@e271828- we can add babel processing step which will allow us to use all modern JS features

**Comment by e271828-** [comment]
Yep, that would be the simple thing. I think I removed them a while back but did not close this issue.

**Comment by CAMOBAP** [comment]
Generally, we have two options how we can integrate babeljs:
1. Include babel into script node as described here https://babeljs.io/setup#installation
1. Preprocessing HTML AoT (before publishing pod)

Due to performance reasons, I think we will proceed with the second way

Out of the box `@babel/cli` doesn't parse embedded JS, so we will need a simple script that will parse <script> nodes from HTML and run babel for it

Still, open question where to do es6 -> es5 conversion. I think the best place is to define it as an extra step in `Podfile` like this:
```
...
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target == "HCaptcha/Core"
            target.new_shell_script_build_phase.shell_script = "fastlane ios prepare_html_template"
        end
    end
end
...
```

During writing this comment I have found https://www.npmjs.com/package/babel-html if it will not work for some reason we may need to write something similar

@e271828- let me know how do you think

**Comment by e271828-** [comment]
We could run `sed` to fix it up first before babel-html, but maybe we just document in the HTML that ES5 is required for now.

**Comment by CAMOBAP** [comment]
@e271828- agree, I will also add a check that our HTML is es5 compliant.

Once if the HTML template becomes more complicated I think it will really make sense to add babel processing

**Comment by CAMOBAP** [comment]
jshintrc looks good to do validation it supports HTML out of the box
