### ISSUE TITLE
CocoaPods did not update on 1.8.0 release

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/HCaptcha-ios-sdk#40]
As in title :)

**Comment by CAMOBAP** [comment]
Yep, because of specific GitHub matching patterns. This should be already fixed in https://github.com/hCaptcha/HCaptcha-ios-sdk/pull/39 (which was merged after 1.8.0 release)

I tried to find some playground to tests our pattern online but no success.

But I also find almost the same pattern in this article https://dev.to/davidb31/for-version-as-git-tag-use-annotated-tag-not-v-prefix-2i4c so I'm relly sure that it must work

**Comment by e271828-** [comment]
OK, guess I forgot about that then. Will close for now.
