### ISSUE TITLE
Integrating iOS SDK

### ISSUE THREAD

**Issue by ahnjac** [hCaptcha/HCaptcha-ios-sdk#45]
Hey all,

I am trying to integrate HCaptcha for the first time into my project, I am running into an issue where I try to configure the web view and its valued as nil.  Installed via CocoaPods. v.2.0.0

I have added my HCAPTCHA Key and HCaptchaDomain - "https://localhost.com" to my info.pList.

If anyone can help me troubleshoot, that would be great.

Thanks!
![Screen Shot 2022-02-21 at 9 37 54 AM](https://user-images.githubusercontent.com/64494079/154986675-5975f7b7-b934-40a5-aaf0-0b026dcc7a32.png)

**Comment by ahnjac** [comment]
Little confused on what to put for domain? any help

**Comment by CAMOBAP** [comment]
Hi, @ahnjac could you please share more details:
 - Which API you are using? Swift? SwiftRx? ObjC?
 - Could you please share the code which interacts with SDK?

**Comment by ahnjac** [comment]
@CAMOBAP 
- I am. using Swift 2.0.0 installed via CocoaPod
![Screen Shot 2022-02-21 at 11 59 35 AM](https://user-images.githubusercontent.com/64494079/155006680-dc2bc6a1-a1f9-4d32-8590-2c01fc0e3334.png)



Thank you

**Comment by CAMOBAP** [comment]
@ahnjac thanks for the information

> I have added my HCAPTCHA Key and HCaptchaDomain - "https://localhost.com/" to my info.pList.

I think the main problem is here, `Info.plist` should contain `http://localhost` (without `.com` and `http` instead `https`)
and looks like this:

```
...
	<key>HCaptchaDomain</key>
	<string>http://localhost</string>
...
```

Also, you can skip `baseURL` argument for `HCaptcha(...)`, because the domain is configured in `Info.plist`

Also, I didn't see the place in the code where you call `validate` to show the captcha, only after this call `configureWebView` will be fired

**Comment by ahnjac** [comment]
@CAMOBAP  - thank you, I got it to work, I have to call validate before calling the configureWebView
