### ISSUE TITLE
Performance: return from `validate` as quickly as possible (pre-cache environment on app start)

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/HCaptcha-ios-sdk#69]
Goal: we want `validate` to return as quickly as possible, especially in passive sitekey case.

I believe this already happens at app start, but there may be some other low-hanging fruit here.

- For example, are we caching assets across invocations? This may require a webview flag.

**Comment by CAMOBAP** [comment]
I have checked the code and didn't find much options to optimize it more.

To be on the same page for now we:
 - Create `WKWebView` instance and load HTML on `HCaptcha.init`
 - There is no reason to use something like https://github.com/bernikovich/WebViewWarmUper because of the previous item
 - For caching policy in `WKWebView` we use the default one - [`NSURLRequestUseProtocolCachePolicy`](https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy/nsurlrequestuseprotocolcachepolicy), it means that it relies on `Cache-Control` Header in response, but as far as I see this header is missing in response `curl -vvv --head https://hcaptcha.com/1/api.js`. I think it's better to send this header than hardcode other policies in SDK ((full list of available policies](https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy))

### Action items

I'm not sure about `Cache-Control` but according to my understanding our backed should send it on `https://hcaptcha.com/1/api.js`

Research about caching is based on links bellow 
 - https://developer.apple.com/documentation/foundation/nsurlrequestcachepolicy/nsurlrequestuseprotocolcachepolicy
 - https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9
 - https://nshipster.com/nsurlcache/
 - https://developer.apple.com/forums/thread/125224
